Home setup
wolox-training/ap-react-native pull request #1
Opened 2017-09-13 19:48 UTC by adrian-ponce-wolox

* Setup project structure
* Add empty home screen with dummy header

![screen shot 2017-09-13 at 4 47 00 pm](https://user-images.githubusercontent.com/25587882/30397403-304ec7c6-98a3-11e7-97dc-4dc0f7bcc454.png)

2017-09-13 21:25 UTC, IgnacioAbadie requested changes
👍  great! just a little changes

2017-09-13 21:25 UTC, IgnacioAbadie commented on w-books/src/App/components/Header/index.js
> +class Header extends Component {
if this component hasnt internal states or function to handle, you can declare it like a function.

```
function Header () {
...
..
...
}

export default Header;
```

2017-09-13 21:25 UTC, IgnacioAbadie commented on w-books/src/assets/styles.css
> +.Home {
Take care to create styles only in components folders.
```
Components
        |  Header
        |          | . index.js
        | .        | . styles.js
screens
   | Home
   |        |  index.js
   |        |  layout.js
   |        |  styles.js

   | OtherScreen
   |        |  index.js
   |        |  layout.js
   |        |  styles.js
```
each component have a style file

2017-09-14 15:43 UTC, IgnacioAbadie commented on w-books/src/App/components/Header/styles.css
> +  box-shadow: 0 5px 5px #DDDDDD;
write color like `#DDD` in this cases.

2017-09-14 15:52 UTC, IgnacioAbadie requested changes

2017-09-14 15:52 UTC, IgnacioAbadie commented on w-books/src/App/components/Header/styles.css
> +.Header {
Use flex to styling the components. You shouldnt need use thinks like positions (relative/absolut)

2017-09-14 15:52 UTC, IgnacioAbadie commented on w-books/src/App/components/Header/styles.css
> +.Header {
Use flex props like:
```
display: flex
flex-direction: row/column
justify-content: center/flex-start/flex-end/space-between/space-around
align-items: center/flex-start/flex-end
```

2017-09-14 15:52 UTC, IgnacioAbadie commented on w-books/src/App/components/Header/styles.css
> +  top: 23px;
So, using flex dont need specific position and `top/bottom/left/right`
Elements order by flex properties

2017-09-14 15:52 UTC, IgnacioAbadie commented on w-books/src/App/components/Header/styles.css
> +  margin-left: 15px;
margin can be unifiqued by
`margin: 0 15px;`

check this
https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

2017-09-14 15:52 UTC, IgnacioAbadie commented on w-books/src/App/screens/Home/styles.css
> +  border-color: #DDDDDD;
`#DDD`;

2017-09-14 18:49 UTC, sbalay approved these changes
Great job! Fix @IgnacioAbadie comments and go!

2017-09-14 18:49 UTC, sbalay commented on w-books/src/App/components/Header/index.js
> +        <img className="Header-button notifications" src={icon_notifications} width="30" height="30" alt="Notifications Icon" />
Always assign width, height and any ui related property using css

2017-09-14 19:20 UTC, adrian-ponce-wolox commented
@IgnacioAbadie Updated the image!

2017-09-14 19:31 UTC, IgnacioAbadie commented on w-books/src/App/components/Header/styles.css
> +  background-color: #FFFFFF;
shorthand color

2017-09-14 19:34 UTC, IgnacioAbadie approved these changes

2017-09-14 19:35 UTC, IgnacioAbadie commented
Great!! :smile: Too better!

2017-09-14 20:07 UTC, merged